AllupFtoB/ViewComponents/FooterViewComponent.cs
using AllupFtoB.DataAccesLayer.Entities;
using AllupFtoB.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AllupFtoB.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public FooterViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var footer = await _dbContext.Footer.ToListAsync();
            var helpDesk = await _dbContext.HelpDesk.ToListAsync();

            var model = new FooterViewModel
            {
                Footers = footer,
                HelpDesks = helpDesk,
            };

            return View(model);
        }
    }
}

AllupFtoB/ViewComponents/HeaderViewComponent.cs
using AllupFtoB.DataAccesLayer.Entities;
using AllupFtoB.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace AllupFtoB.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly AppDbContext _dbContext;

        public HeaderViewComponent(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var headers = await _dbContext.Headers.ToListAsync();
            var product = await _dbContext.Products.ToListAsync();

            var model = new HeaderViewModel
            {
                Headers = headers,
                Products = product,
            };

            return View(model);
        }
    }
}

AllupFtoB/Views/Shared/_BasketPartial.cshtml
@model List<BasketViewModel>

@foreach (var item in Model)
{
    <li>
        <div class="single-cart-item d-flex">
            <div class="cart-item-thumb">
                <a href="single-product.html"><img src="@item.ImageUrl" alt="product"></a>
                <span class="product-quantity">@item.Count</span>
            </div>
            <div class="cart-item-content media-body">
                <h5 class="product-name"><a href="single-product.html">@item.Title</a></h5>
                <span class="product-price">€@item.Price</span>
                <a href="#" class="product-close"><i class="fal fa-times"></i></a>
            </div>
        </div>
    </li>
}

AllupFtoB/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:46:32 GMT -->
<head>
    <meta charset="utf-8">

    <!--====== Title ======-->
    <title>Allup - Electronics Responsive eCommerce HTML Template.</title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!--====== Favicon Icon ======-->
    <link rel="shortcut icon" href="~/images/favicon.png" type="image/png">


    <!-- CSS
    ============================================ -->
    <!--===== Vendor CSS (Bootstrap & Icon Font) =====-->

    <link rel="stylesheet" href="~/css/plugins/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/plugins/ionicons.min.css">
    <link rel="stylesheet" href="~/css/plugins/fontawesome.min.css">

    <!--===== Plugins CSS (All Plugins Files) =====-->

    <link rel="stylesheet" href="~/css/plugins/slick.css">
    <link rel="stylesheet" href="~/css/plugins/animate.css">
    <link rel="stylesheet" href="~/css/plugins/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/plugins/default.css">

    <!--====== Main Style CSS ======-->
    <link rel="stylesheet" href="~/css/style.css">


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->
    <!-- <link rel="stylesheet" href="~/css/vendor/plugins.min.css">
    <link rel="stylesheet" href="~/css/style.min.css"> -->

</head>

<body>

    <!--====== PRELOADER PART START ======-->

    <div id="preloader">
        <div class="preloader">
            <span></span>
            <span></span>
        </div>
    </div>

    <!--====== PRELOADER PART ENDS ======-->

    @await Component.InvokeAsync("Header")

            @RenderBody()

    <!--====== Footer Part Start ======-->

    @await Component.InvokeAsync("Footer")

    <!--====== Footer Part Ends ======-->

    <!--====== BACK TOP TOP PART START ======-->

    <a href="#" class="back-to-top"><i class="ion-android-arrow-up"></i></a>

    <!--====== BACK TOP TOP PART ENDS ======-->
    <!--====== Vendors js ======-->
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/vendor/modernizr-3.7.1.min.js"></script>

    <!--====== Plugins js ======-->
    <script src="~/js/plugins/popper.min.js"></script>
    <script src="~/js/plugins/bootstrap.min.js"></script>
    <script src="~/js/plugins/slick.min.js"></script>
    <script src="~/js/plugins/jquery.countdown.min.js"></script>
    <script src="~/js/plugins/jquery-ui.min.js"></script>


    <!--====== Use the minified version files listed below for better performance and remove the files listed above ======-->
    <!-- <script src="~/js/plugins.min.js"></script> -->
    <!--====== Main Activation js ======-->
    <script src="~/js/main.js"></script>




</body>


<!-- Mirrored from demo.hasthemes.com/allup/allup/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 04 Sep 2020 10:47:16 GMT -->
</html>

AllupFtoB/Views/Shared/_SearchProductPartial.cshtml
@model List<Product>

    @foreach (var item in Model)
{
    <li class="d-flex px-3">
            @item.Title
    </li>
}